scrapy crawl hw_cases
scrapy crawl hw_cpucooler
scrapy crawl hw_cpu
scrapy crawl hw_gpu
scrapy crawl hw_ram
scrapy crawl hw_opticaldrive
scrapy crawl hw_motherboard
scrapy crawl hw_power_supply
scrapy crawl hw_storage